apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: fussy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: fussy-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: fussy-{{ .Release.Name }}
    spec:
      containers:
      - name: fussy
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
          name: http

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
