apiVersion: v1
kind: Service
metadata:
  labels:
    app: fussy
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    name: http
  selector:
    app: fussy-{{ .Release.Name }}
